
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANuIli8dMcOc2zpQX6vxamldA18WIsROU',
    appId: '1:618718312464:web:720e0c53b406d6980fb295',
    messagingSenderId: '618718312464',
    projectId: 'taskapp-cb3ce',
    authDomain: 'taskapp-cb3ce.firebaseapp.com',
    storageBucket: 'taskapp-cb3ce.appspot.com',
    measurementId: 'G-ZZQRXFCY5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3IS6kw65GTKUfMFDcw4QzyjWYA-HXCg',
    appId: '1:618718312464:android:9581eca567cbf1bb0fb295',
    messagingSenderId: '618718312464',
    projectId: 'taskapp-cb3ce',
    storageBucket: 'taskapp-cb3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ6cNy628dldiqwR9nVlokSq1qk55CmTE',
    appId: '1:618718312464:ios:9208cd800f811af70fb295',
    messagingSenderId: '618718312464',
    projectId: 'taskapp-cb3ce',
    storageBucket: 'taskapp-cb3ce.appspot.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ6cNy628dldiqwR9nVlokSq1qk55CmTE',
    appId: '1:618718312464:ios:f2714de9bf3e43bf0fb295',
    messagingSenderId: '618718312464',
    projectId: 'taskapp-cb3ce',
    storageBucket: 'taskapp-cb3ce.appspot.com',
    iosBundleId: 'com.example.tp2.RunnerTests',
  );
}
